apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hash
spec:
  selector:
    matchLabels:
      app: node-hash
  template:
    metadata:
      labels:
        app: node-hash
    spec:
      containers:
        - name: node-hash
          image: node-hash
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: '8080'
          resources:
            limits:
              memory: '64Mi'
              cpu: '128m'
          ports:
            - containerPort: 8080
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: node-hash
spec:
  selector:
    app: node-hash
  ports:
    - port: 80
      targetPort: http
